[package]
name = "cow-vs-owned"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = { version = "0.4", features = ["csv_output"] }

[[bench]]
name = "cow_vs_string"
harness = false
